package org.apache.rocketmq.connect.http.sink.constant;

public class HttpConstant {
    
    public static final String URL_PATTERN_CONSTANT = "urlPattern";
    public static final String METHOD_CONSTANT = "method";
    public static final String QUERY_STRING_PARAMETERS_CONSTANT = "queryStringParameters";
    public static final String HEADER_PARAMETERS_CONSTANT = "headerParameters";
    public static final String BODYS_CONSTANT = "bodys";
    public static final String AUTH_TYPE_CONSTANT = "authType";
    public static final String BASIC_USER_CONSTANT = "basicUser";
    public static final String BASIC_PASSWORD_CONSTANT = "basicPassword";
    public static final String OAUTH2_ENDPOINT_CONSTANT = "oauth2Endpoint";
    public static final String OAUTH2_CLIENTID_CONSTANT = "oauth2ClientId";
    public static final String OAUTH2_CLIENTSECRET_CONSTANT = "oauth2ClientSecret";
    public static final String OAUTH2_HTTP_METHOD_CONSTANT = "oauth2HttpMethod";
    public static final String PROXY_TYPE_CONSTANT = "proxyType";
    public static final String PROXY_HOST_CONSTANT = "proxyHost";
    public static final String PROXY_PORT_CONSTANT = "proxyPort";
    public static final String PROXY_USER_CONSTANT = "proxyUser";
    public static final String PROXY_PASSWORD_CONSTANT = "proxyPassword";
    public static final String TIMEOUT_CONSTANT = "timeout";
    public static final String HTTP_PATH_VALUE = "httpPathValue";
    public static final String HTTP_QUERY_VALUE = "httpQuery";
    public static final String HTTP_METHOD = "httpMethod";
    public static final String HTTP_HEADER = "httpHeader";
    public static final String GET_METHOD = "GET";
    public static final String DELETE_METHOD = "DELETE";
    public static final String POST_METHOD = "POST";
    public static final String PUT_METHOD = "PUT";
    public static final String HEAD_METHOD = "HEAD";
    public static final String TRACE_METHOD = "TRACE";
    public static final String PATCH_METHOD = "PATCH";
    public static final String OPTIONS_METHOD = "OPTIONS";
    public static final String AUTHORIZATION = "Authorization";
    public static final String SUCCESS = "Success";
    public static final String API_KEY_NAME = "apiKeyName";
    public static final String API_KEY_VALUE = "apiKeyValue";
    public static final String OAUTH_BASIC_KEY = "oauthBasicKey";
    public static final String OAUTH_BASIC_VALUE = "oauthBasicValue";
    public static final String API_DESTINATION_NAME = "apiDestinationName";
    public static final String REGION_ID = "regionId";
    public static final String ACCESSKEY_ID = "accessKeyId";
    public static final String ACCESS_KEY_SECRET = "accessKeySecret";
    public static final String ACCOUNT_ID = "accountId";
    public static final String ENDPOINT = "endpoint";
    public static final String PUSH_CERT_PRIVATE_KEY = "pushCertPrivateKey";
    public static final String PUSH_CERT_SIGN_METHOD = "pushCertSignMethod";
    public static final String PUSH_CERT_SIGN_VERSION = "pushCertSignVersion";
    public static final String PUSH_CERT_PUBLIC_KEY_URL = "pushCertPublicKeyUrl";
}
